### ISSUE TITLE
Logic of the code

### ISSUE THREAD

**Issue by roshu10** [gilt/s3-sftp-bridge#7]
Hi, 
I'm dont know about nodejs. 
I have doubt on saving files from getting new files from sftp server to S3. 
How does polling works??

**Comment by rlmartin** [comment]
Sorry, I'm not understanding your issue. For polling, you will need to manually add a scheduled CloudWatch Event at the cadence you would like to poll. See https://github.com/gilt/s3-sftp-bridge#sftp--s3

**Comment by roshu10** [comment]
Thanks for the response.

My question is, how to get the list of recently added file list from SFTP server.

We have an SFTP server with thousands of files.

Lets imagine 10-15 files gets added for every 15 minute.

How do it get the names of these newly added 10-15 files from SFTP server ?

**Comment by rlmartin** [comment]
After copying files from SFTP => S3, this script moves the copied files to a '.done' subdirectory. So when it polls the directory the next time, it won't see the already-copied files at the top level. This is focused on being an automated sync that assumes you want things in S3 - which is why it manipulates the state of the origin SFTP folder. If you need the files to remain untouched in SFTP, you'll need to either fork this repo and tweak the logic, or find another solution.

**Comment by roshu10** [comment]
Thank you :)
Just one question, you are moving files to .done subdirectory in sftp folder right ?

**Comment by rlmartin** [comment]
Correct
